"""initial schema

Revision ID: 213a6205496b
Revises: 
Create Date: 2026-09-07 08:11:10.576785
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '213a6205496b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('type', sa.Enum('person', 'organization', 'location', 'event', 'other', name='entitytype', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'type', name='uq_entity_name_type')
    )
    op.create_table('sources',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('homepage_url', sa.String(length=500), nullable=True),
    sa.Column('feed_url', sa.String(length=500), nullable=False),
    sa.Column('feed_type', sa.Enum('rss', 'atom', 'json', 'api', name='feedtype', native_enum=False, length=16), nullable=False),
    sa.Column('default_category', sa.Enum('iran', 'world', 'politics', 'economy', 'technology', 'ai', 'culture', name='category', native_enum=False, length=16), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('allow_full_content', sa.Boolean(), nullable=False),
    sa.Column('allow_image', sa.Boolean(), nullable=False),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('usage_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stories',
    sa.Column('headline_fa', sa.String(length=500), nullable=True),
    sa.Column('summary_fa', sa.Text(), nullable=True),
    sa.Column('what_happened_fa', sa.Text(), nullable=True),
    sa.Column('why_it_matters_fa', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('iran', 'world', 'politics', 'economy', 'technology', 'ai', 'culture', name='category', native_enum=False, length=16), nullable=True),
    sa.Column('status', sa.Enum('draft', 'processing', 'published', 'flagged', name='storystatus', native_enum=False, length=16), nullable=False),
    sa.Column('iran_relevance', sa.Enum('high', 'medium', 'low', 'none', name='iranrelevance', native_enum=False, length=8), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stories_category'), ['category'], unique=False)
        batch_op.create_index('ix_stories_feed_order', ['status', 'importance_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_importance_score'), ['importance_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_status'), ['status'], unique=False)

    op.create_table('topics',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name_fa', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('articles',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('article_url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('category', sa.Enum('iran', 'world', 'politics', 'economy', 'technology', 'ai', 'culture', name='category', native_enum=False, length=16), nullable=True),
    sa.Column('raw_content_if_permitted', sa.Text(), nullable=True),
    sa.Column('image_url_if_permitted', sa.String(length=1000), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_url'),
    sa.UniqueConstraint('hash')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_articles_source_published', ['source_id', 'published_at'], unique=False)

    op.create_table('source_views',
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('original_headline', sa.String(length=1000), nullable=True),
    sa.Column('article_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewpoint_fa', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_views_story_id'), ['story_id'], unique=False)

    op.create_table('statements',
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('fact', 'uncertainty', 'agreement', 'disagreement', name='statementkind', native_enum=False, length=16), nullable=False),
    sa.Column('text_fa', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statements_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_statements_story_id'), ['story_id'], unique=False)

    op.create_table('story_topics',
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'topic_id', name='uq_story_topic')
    )
    with op.batch_alter_table('story_topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_topics_story_id'), ['story_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_topics_topic_id'), ['topic_id'], unique=False)

    op.create_table('user_follows',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_user_topic')
    )
    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_follows_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_follows_user_id'), ['user_id'], unique=False)

    op.create_table('story_articles',
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'article_id', name='uq_story_article')
    )
    with op.batch_alter_table('story_articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_articles_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_articles_story_id'), ['story_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_articles_story_id'))
        batch_op.drop_index(batch_op.f('ix_story_articles_article_id'))

    op.drop_table('story_articles')
    with op.batch_alter_table('user_follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_follows_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_follows_topic_id'))

    op.drop_table('user_follows')
    with op.batch_alter_table('story_topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_topics_topic_id'))
        batch_op.drop_index(batch_op.f('ix_story_topics_story_id'))

    op.drop_table('story_topics')
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statements_story_id'))
        batch_op.drop_index(batch_op.f('ix_statements_kind'))

    op.drop_table('statements')
    with op.batch_alter_table('source_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_views_story_id'))

    op.drop_table('source_views')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index('ix_articles_source_published')
        batch_op.drop_index(batch_op.f('ix_articles_source_id'))

    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('topics')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stories_status'))
        batch_op.drop_index(batch_op.f('ix_stories_importance_score'))
        batch_op.drop_index('ix_stories_feed_order')
        batch_op.drop_index(batch_op.f('ix_stories_category'))

    op.drop_table('stories')
    op.drop_table('sources')
    op.drop_table('entities')
    # ### end Alembic commands ###
