"""add ingestion_logs

Revision ID: 28b3d9ac1231
Revises: 213a6205496b
Create Date: 2026-09-07 08:46:33.374356
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '28b3d9ac1231'
down_revision: Union[str, None] = '213a6205496b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_logs',
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_logs_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingestion_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_logs_source_id'))

    op.drop_table('ingestion_logs')
    # ### end Alembic commands ###
